paths:
  /v3/deployments:
    get:
      summary: List deployments
      description: Retrieve a paginated list of deployments. Deployments represent updates to applications with zero downtime.
      tags:
        - deployments
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
        - name: per_page
          in: query
          description: Number of results per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 5000
        - name: order_by
          in: query
          description: Field by which to order results
          required: false
          schema:
            type: string
            enum: [created_at, updated_at, -created_at, -updated_at]
        - name: states
          in: query
          description: Filter by deployment states (comma-separated)
          required: false
          schema:
            type: string
        - name: app_guids
          in: query
          description: Filter by app GUIDs (comma-separated)
          required: false
          schema:
            type: string
        - name: status_reasons
          in: query
          description: Filter by status reasons (comma-separated)
          required: false
          schema:
            type: string
        - name: status_values
          in: query
          description: Filter by status values (comma-separated)
          required: false
          schema:
            type: string
        - name: label_selector
          in: query
          description: Filter by label selector
          required: false
          schema:
            type: string
        - name: created_ats
          in: query
          description: Filter by creation timestamps
          required: false
          schema:
            type: string
        - name: updated_ats
          in: query
          description: Filter by update timestamps
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paginated list of deployments
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                  resources:
                    type: array
                    items:
                      $ref: '#/components/schemas/Deployment'
        '401':
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/UnexpectedError'

    post:
      summary: Create a deployment
      description: Create a new deployment for an app. This will deploy a new droplet and/or update the app's configuration with zero downtime.
      tags:
        - deployments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - relationships
              properties:
                droplet:
                  type: object
                  properties:
                    guid:
                      type: string
                      format: uuid
                      description: GUID of the droplet to deploy
                revision:
                  type: object
                  properties:
                    guid:
                      type: string
                      format: uuid
                      description: GUID of the revision to deploy
                    version:
                      type: integer
                      description: Version number of the revision
                strategy:
                  type: string
                  enum: [rolling, recreate, canary]
                  default: rolling
                  description: Deployment strategy to use
                options:
                  type: object
                  properties:
                    max_in_flight:
                      type: integer
                      description: Maximum number of instances to update simultaneously (rolling strategy)
                      minimum: 1
                      default: 1
                metadata:
                  type: object
                  properties:
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                relationships:
                  type: object
                  required:
                    - app
                  properties:
                    app:
                      type: object
                      required:
                        - data
                      properties:
                        data:
                          type: object
                          required:
                            - guid
                          properties:
                            guid:
                              type: string
                              format: uuid
                              description: GUID of the app to deploy
      responses:
        '201':
          description: The created deployment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        default:
          $ref: '#/components/responses/UnexpectedError'
      security:
        - bearerAuth: []
      x-roles:
        - cloud_controller.admin
        - space_developer
        - space_supporter

  /v3/deployments/{guid}:
    get:
      summary: Get a deployment
      description: Retrieve details of a specific deployment
      tags:
        - deployments
      parameters:
        - name: guid
          in: path
          required: true
          description: The GUID of the deployment
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The deployment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/UnexpectedError'

    patch:
      summary: Update a deployment
      description: Update metadata for a deployment
      tags:
        - deployments
      parameters:
        - name: guid
          in: path
          required: true
          description: The GUID of the deployment
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                metadata:
                  type: object
                  properties:
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
      responses:
        '200':
          description: The updated deployment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        default:
          $ref: '#/components/responses/UnexpectedError'
      security:
        - bearerAuth: []
      x-roles:
        - cloud_controller.admin
        - space_developer
        - space_supporter

  /v3/deployments/{guid}/actions/cancel:
    post:
      summary: Cancel a deployment
      description: Cancel an active deployment. This will stop the deployment process and roll back to the previous version.
      tags:
        - deployments
      parameters:
        - name: guid
          in: path
          required: true
          description: The GUID of the deployment
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The canceled deployment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        default:
          $ref: '#/components/responses/UnexpectedError'
      security:
        - bearerAuth: []
      x-roles:
        - cloud_controller.admin
        - space_developer
        - space_supporter

  /v3/deployments/{guid}/actions/continue:
    post:
      summary: Continue a deployment
      description: Continue a paused deployment (e.g., after canary phase)
      tags:
        - deployments
      parameters:
        - name: guid
          in: path
          required: true
          description: The GUID of the deployment
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The continued deployment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        default:
          $ref: '#/components/responses/UnexpectedError'
      security:
        - bearerAuth: []
      x-roles:
        - cloud_controller.admin
        - space_developer
        - space_supporter

components:
  schemas:
    Deployment:
      type: object
      required:
        - guid
        - created_at
        - updated_at
        - state
        - status
        - strategy
        - droplet
        - previous_droplet
        - new_processes
        - revision
        - metadata
        - relationships
        - links
      properties:
        guid:
          type: string
          format: uuid
          description: Unique identifier for the deployment
        created_at:
          type: string
          format: date-time
          description: The time the deployment was created
        updated_at:
          type: string
          format: date-time
          description: The time the deployment was last updated
        state:
          type: string
          enum: [DEPLOYING, DEPLOYED, CANCELING, CANCELED]
          description: Current state of the deployment
        status:
          type: object
          properties:
            value:
              type: string
              enum: [ACTIVE, FINALIZED, CANCELING]
              description: Status value
            reason:
              type: string
              nullable: true
              enum: [DEPLOYING, CANCELED, SUPERSEDED, DEPLOYED, DEGENERATE]
              description: Reason for the current status
            details:
              type: object
              nullable: true
              description: Additional status details
        strategy:
          type: string
          enum: [rolling, recreate, canary]
          description: Deployment strategy being used
        droplet:
          type: object
          properties:
            guid:
              type: string
              format: uuid
              description: GUID of the droplet being deployed
        previous_droplet:
          type: object
          nullable: true
          properties:
            guid:
              type: string
              format: uuid
              description: GUID of the previous droplet
        new_processes:
          type: array
          description: List of new processes created by this deployment
          items:
            type: object
            properties:
              guid:
                type: string
                format: uuid
              type:
                type: string
        revision:
          type: object
          nullable: true
          properties:
            guid:
              type: string
              format: uuid
              description: GUID of the revision being deployed
            version:
              type: integer
              description: Version number of the revision
        options:
          type: object
          properties:
            max_in_flight:
              type: integer
              description: Maximum number of instances to update simultaneously
        metadata:
          type: object
          properties:
            labels:
              type: object
              additionalProperties:
                type: string
            annotations:
              type: object
              additionalProperties:
                type: string
        relationships:
          type: object
          properties:
            app:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    guid:
                      type: string
                      format: uuid
                      description: GUID of the app being deployed
        links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  description: URL to this deployment
            app:
              type: object
              properties:
                href:
                  type: string
                  description: URL to the app
            cancel:
              type: object
              properties:
                href:
                  type: string
                  description: URL to cancel the deployment
                method:
                  type: string
                  enum: [POST]

    Pagination:
      type: object
      properties:
        total_results:
          type: integer
        total_pages:
          type: integer
        first:
          type: object
          properties:
            href:
              type: string
        last:
          type: object
          properties:
            href:
              type: string
        next:
          type: object
          nullable: true
          properties:
            href:
              type: string
        previous:
          type: object
          nullable: true
          properties:
            href:
              type: string

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT