extends:
  - spectral:oas

# Custom rules for CAPI OpenAPI specification
rules:
  # Disable some overly strict default rules
  oas3-unused-component: off
  operation-tag-defined: warn
  oas3-valid-media-example: warn
  info-contact: warn
  
  # CAPI-specific naming conventions
  capi-operation-id-format:
    description: Operation IDs should follow CAPI naming convention
    severity: error
    given: "$.paths[*][*].operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[a-zA-Z][a-zA-Z0-9_]*$"

  capi-tag-description:
    description: All tags must have descriptions
    severity: warn
    given: "$.tags[*]"
    then:
      field: description
      function: truthy

  # Security requirements
  capi-security-defined:
    description: API must define security schemes
    severity: error
    given: "$"
    then:
      field: components.securitySchemes
      function: truthy

  # Disabled due to false positives - security is already defined
  capi-endpoint-security: off

  # Pagination standards - only for list operations
  capi-pagination-parameters:
    description: List endpoints should have standard pagination parameters
    severity: warn
    given: "$.paths[?(!@property.match(/\\{[^}]+\\}$/))].get"
    then:
      field: parameters
      function: defined

  # Error response structure
  capi-error-response-format:
    description: Error responses must follow CAPI error format
    severity: warn
    given: "$.paths[*][*].responses[4*,5*].content.application/json.schema"
    then:
      function: defined

  # Parameter requirements
  capi-parameter-examples:
    description: Parameters should include examples
    severity: info
    given: 
      - "$.paths[*][*].parameters[?(@.schema && @.in == 'query')]"
      - "$.components.parameters[?(@.schema && @.in == 'query')]"
    then:
      field: example
      function: defined

  # CAPI-specific path conventions
  # Disabled due to false positives
  capi-path-format: off

  # Response description requirements
  capi-response-descriptions:
    description: All responses must have descriptions
    severity: error
    given: "$.paths[*][*].responses[*]"
    then:
      field: description
      function: truthy