# This workflow has been replaced by test-comprehensive.yml
# Keeping this file for backwards compatibility

name: Test SDK Generation (Deprecated)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'CAPI version to test'
        required: true
        type: string

jobs:
  redirect:
    name: Redirect to comprehensive testing
    uses: ./.github/workflows/test-comprehensive.yml
    with:
      version: ${{ inputs.version }}